name = "Synchronizers"
uuid = "9279c0cf-0ddb-4a8a-93c9-19d312620a08"
authors = ["akels <akels14@gmail.com>"]
version = "0.1.0"

[deps]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
